[package]
name = "credit_protocol"
version = "1.0.1"
authors = ["Credit Protocol Team"]

[addresses]
credit_protocol = "0xceb67803c3af67e2031e319f021e693ead697dda75e59a7b85a7e75a1cda4d78"

[dev-addresses]
credit_protocol = "0xceb67803c3af67e2031e319f021e693ead697dda75e59a7b85a7e75a1cda4d78"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]