[package]
name = "credit_protocol"
version = "1.0.0"
authors = ["Credit Protocol Team"]

[addresses]
credit_protocol = "0x636df8ee3f59dfe7d17ff23d3d072b13c38db48740ac18c27f558e6e26165172"

[dev-addresses]
credit_protocol = "0x7dab2b468867d46e5a1968ffa045d1308b010e6e1eece081172c72c3f35c4f5e"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]